pr_checks:
  title:
    - name: 'prefix_check'
      regex: '^(chore|ci|content|docs|feat|fix|refactor|revert|test|ui)(\([\w\-\.]+\))?(!)?:'
      message_if_not_matching: 'PR title must start with "fix:", "feat:", or one of the other commit types specified in [pr-checks-config.yml](https://github.com/fylein/fyle-integrations-app-e2e-tests/blob/master/.github/pr-checks-config.yml). See [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) for more information.'

  description:
    - name: 'clickup_check'
      regex: '(?i)app.clickup.com'
      message_if_not_matching: 'PR description must contain a link to a ClickUp (case-insensitive)'
